# Keeping separate publish workflows for beta and latest, as it
# makes it easier to see in 'Actions' which workflow ran

name: NPM publish latest

on:
  release:
    types: [published]

jobs:
  publish:
    if: "!github.event.release.prerelease"

    runs-on: ubuntu-latest

    outputs:
      NPM_PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and build 🔧
        run: npm ci && npm run build

      - name: Publish package to NPM - Latest 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Return NPM Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

  post-release-to-discord:
    name: Discord Webhooks

    needs: [publish]

    # uses: homebridge/.github/.github/workflows/discord-webhooks.yml@latest
    uses: justjam2013/homebridge-virtual-accessories/.github/workflows/discord-webhooks.yml@latest
    with:
      title: Virtual Accessories for Homebridge - Latest Release
      description: |
        Version `${{ github.event.release.tag_name }}`
      url: 'https://github.com/justjam2013/homebridge-virtual-accessories/releases/tag/v${{ needs.publish.outputs.NPM_PACKAGE_VERSION }}'
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
